"""
Django settings for mymental_backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ
from datetime import timedelta
from pythonjsonlogger import jsonlogger
from .observability import RequestIdFilter

try:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
except Exception:  # pragma: no cover
    sentry_sdk = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize environment variables
env = environ.Env(
    DEBUG=(bool, False)
)

environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-@c!-##lgmk9ep8fua@+(jvv)*!s%+722g^gp!ovtp=l=575vkr')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default=True)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1', '0.0.0.0'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'channels',
    'graphene_django',
    # Local apps
    'users',
    'chatbot',
    'counselor',
    'analytics',
    'compliance',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'mymental_backend.middleware.request_id_middleware.RequestIdMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mymental_backend.security_headers.SecurityHeadersMiddleware',
    'mymental_backend.middleware.performance_middleware.PerformanceMiddleware',
    'mymental_backend.middleware.audit_middleware.AuditMiddleware',
]

ROOT_URLCONF = 'mymental_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mymental_backend.wsgi.application'


# Database Configuration
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# PostgreSQL - For structured data (users, counselors, conversations)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME', default='mymental_db'),
        'USER': env('DB_USER', default='postgres'),
        'PASSWORD': env('DB_PASSWORD', default='postgres'),
        'HOST': env('DB_HOST', default='localhost'),
        'PORT': env('DB_PORT', default='5432'),
        # Connection pooling and optimization
        'OPTIONS': {
            'connect_timeout': 10,
            'options': '-c statement_timeout=30000',  # 30 second query timeout
        },
        # Connection reuse for performance
        'CONN_MAX_AGE': 600,  # Reuse connections for 10 minutes
        # Connection pool settings (handled by pgbouncer or django-db-pool)
        'ATOMIC_REQUESTS': False,  # Better performance without transactions
    },
    # MongoDB as first-class DB via django-mongodb-backend
    'mongodb': {
        'ENGINE': 'django_mongodb_backend',
        # Prefer connection string if provided; else fall back to host/port
        'HOST': env('MONGO_URI', default=''),
        'NAME': env('MONGO_DB_NAME', default='mymental_chat'),
        # If HOST is empty, ENGINE will use default localhost from driver unless provided via options
    }
}

# Database Routing for Master-Slave Pattern
DATABASE_ROUTERS = ['mymental_backend.routers.DatabaseRouter']

# MongoDB Configuration - For chat messages and real-time data
MONGO_SETTINGS = {
    'host': env('MONGO_HOST', default='localhost'),
    'port': int(env('MONGO_PORT', default='27017')),
    'database': env('MONGO_DB_NAME', default='mymental_chat'),
    'username': env('MONGO_USER', default=''),
    'password': env('MONGO_PASSWORD', default=''),
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# AuthGuard integration (use AuthGuard as identity provider)
AUTHGUARD_INTEGRATION_ENABLED = env.bool('AUTHGUARD_INTEGRATION_ENABLED', default=False)
AUTHGUARD_BASE_URL = env('AUTHGUARD_BASE_URL', default='')
AUTHGUARD_JWKS_URL = env('AUTHGUARD_JWKS_URL', default='')
AUTHGUARD_ISSUER = env('AUTHGUARD_ISSUER', default='authguard')
AUTHGUARD_AUDIENCE = env('AUTHGUARD_AUDIENCE', default='authguard')
AUTHGUARD_TLS_INSECURE_SKIP_VERIFY = env.bool('AUTHGUARD_TLS_INSECURE_SKIP_VERIFY', default=False)
AUTHGUARD_CLIENT_TIMEOUT_SECONDS = env.int('AUTHGUARD_CLIENT_TIMEOUT_SECONDS', default=10)
AUTHGUARD_COOKIE_SECURE = env.bool('AUTHGUARD_COOKIE_SECURE', default=False)
AUTHGUARD_JWT_CLOCK_SKEW_SECONDS = env.int('AUTHGUARD_JWT_CLOCK_SKEW_SECONDS', default=30)
AUTHGUARD_JWKS_CACHE_TTL_SECONDS = env.int('AUTHGUARD_JWKS_CACHE_TTL_SECONDS', default=3600)

# Derive JWKS URL from base URL if not explicitly set.
if AUTHGUARD_INTEGRATION_ENABLED and AUTHGUARD_JWKS_URL == '' and AUTHGUARD_BASE_URL:
    AUTHGUARD_JWKS_URL = AUTHGUARD_BASE_URL.rstrip('/') + '/.well-known/jwks.json'

# Authentication classes switch based on whether we're using AuthGuard.
if AUTHGUARD_INTEGRATION_ENABLED:
    DEFAULT_AUTHENTICATION_CLASSES = [
        'users.authguard_authentication.AuthGuardJWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ]
else:
    DEFAULT_AUTHENTICATION_CLASSES = [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ]

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': DEFAULT_AUTHENTICATION_CLASSES,
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
        'mymental_backend.rate_limiting.IPRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '2000/hour',
        'anon': '200/hour',
        'ip': '100/hour',
    },
    # Pagination for performance
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    # Response rendering optimization
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# SimpleJWT configuration (adjust lifetimes via env in production)
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[
    'http://localhost:3000',
    'http://127.0.0.1:3000',
])

CORS_ALLOW_CREDENTIALS = True

# CSRF Configuration
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[
    'http://localhost:3000',
    'http://127.0.0.1:3000',
])

CSRF_COOKIE_SECURE = env('CSRF_COOKIE_SECURE', default=False)  # Set True in production with HTTPS
SESSION_COOKIE_SECURE = env('SESSION_COOKIE_SECURE', default=False)  # Set True in production with HTTPS
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'

# Redis Caching Configuration
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': env('REDIS_URL', default='redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
            'IGNORE_EXCEPTIONS': True,  # Don't fail if Redis is down
        },
        'KEY_PREFIX': 'mymental',
        'TIMEOUT': 300,  # Default timeout: 5 minutes
    }
}

# Session caching for performance
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'

# Logging configuration (structured JSON logs with request_id)
LOG_LEVEL = env('LOG_LEVEL', default='INFO')
LOG_JSON_INDENT = None if env('LOG_COMPACT', default='1') == '1' else 2

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'request_id': {
            '()': RequestIdFilter,
        },
    },
    'formatters': {
        'json': {
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
            'fmt': (
                'timestamp asctime levelname name message '
                'request_id pathname lineno funcName process thread '
                'module'
            ),
        },
        'console': {
            'format': '[%(levelname)s] %(name)s: %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'filters': ['request_id'],
            'formatter': 'json',
            'level': LOG_LEVEL,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {'level': LOG_LEVEL, 'handlers': ['console'], 'propagate': True},
        'audit': {'level': 'INFO', 'handlers': ['console'], 'propagate': False},
    },
}

# Sentry configuration (enabled when SENTRY_DSN is set)
SENTRY_DSN = env('SENTRY_DSN', default='')
SENTRY_TRACES = float(env('SENTRY_TRACES', default='0.2'))
SENTRY_PROFILES = float(env('SENTRY_PROFILES', default='0.0'))
ENVIRONMENT = env('ENVIRONMENT', default='development')

if SENTRY_DSN and sentry_sdk:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        traces_sample_rate=SENTRY_TRACES,
        profiles_sample_rate=SENTRY_PROFILES,
        environment=ENVIRONMENT,
        send_default_pii=False,
        enable_tracing=True,
    )

# Celery Configuration
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Celery Beat Schedule
try:
    from .celerybeat_schedule import CELERY_BEAT_SCHEDULE
except ImportError:
    # Celery not installed, use empty schedule
    CELERY_BEAT_SCHEDULE = {}

# GraphQL Configuration
GRAPHENE = {
    'SCHEMA': 'graphql_app.schema.schema',
    'MIDDLEWARE': [
        'graphql_jwt.middleware.JSONWebTokenMiddleware',
    ],
}

# Logging Configuration
LOGGING_DIR = BASE_DIR / 'logs'
LOGGING_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'json': {
            'format': '{"time": "%(asctime)s", "name": "%(name)s", "level": "%(levelname)s", "message": "%(message)s"}',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGGING_DIR / 'django.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'audit_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGGING_DIR / 'audit.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 10,  # Keep more audit logs
            'formatter': 'json',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGGING_DIR / 'error.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': env('DJANGO_LOG_LEVEL', default='INFO'),
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'audit': {
            'handlers': ['audit_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'chatbot': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'mymental_backend': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Firebase Cloud Messaging (optional)
FCM_SERVER_KEY = os.getenv('FCM_SERVER_KEY', '')
